"""
GigScore — Agent 3: Social Trust Graph + Behavioral Scoring
============================================================
Barclays Hack-O-Hire 2026 · Team GigScore · Plaksha University

Reads:   agent0_features.csv  (from Agent 0)
         agent0_output.json   (transactions for red flag detection)

Outputs: agent3_output.json   (behavioral score + score_adjustment for Agent 4)

What this agent does:
─────────────────────
1. Computes a behavioral score (0–10) from 3 feature groups:
      Group A: Social Trust Graph   (rootedness, obligations, stability)
      Group B: Behavioral Velocity  (UPI + credit + loan signals)
      Group C: Derived Interactions (cross-feature non-linear signals)

2. Detects red flags from transaction narrations:
      gambling       — Dream11, rummy, betting, casino
      rent_stress    — no rent payment found in statement
      spend_balance  — total debits > total credits (net outflow)

3. Computes behavioral_delta vs cohort baseline
   and maps it to a score_adjustment (+0 to +5) for Agent 4.

4. Outputs social_trust_score (0–100) for Agent 4 Layer 2 blend.

Score adjustment logic (mirrors AGENT0-RESULT-final5.json):
   behavioral_delta > 3.5  → +4
   behavioral_delta > 2.5  → +3
   behavioral_delta > 1.0  → +2
   behavioral_delta > 0.0  → +1
   else                    → +0
   Any confirmed red flag reduces adjustment by 1 per flag (min 0)
"""

import json
import re
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')

# ── Hardcoded file names ──────────────────────────────────────────────────
FEATURES_CSV   = "agent0_features.csv"
OUTPUT_JSON_A0 = "agent0_output.json"
OUTPUT_JSON    = "agent3_output.json"
MEDIANS_JSON   = "training_medians.json"         # generated by agents_012.py --mode train
AGENT2_RESULT  = "agent2_result_raju_sharma.json" # generated by agents_012.py --mode score

# ── Cohort portfolio baseline (from master dataset training) ─────────────
PORTFOLIO_SAFE_RATE = 0.891559  # 89.16% non-default rate in cohort

# ── Red flag patterns (from transaction narrations) ──────────────────────
RED_FLAG_PATTERNS = {
    "gambling": {
        "patterns": [
            re.compile(r"\bDREAM\s*11\b|\bRUMMY\b|\bBETTING\b|\bCASINO\b|\bMPL\b|\bWINZO\b|\bGAME\s*CASH\b", re.I),
        ],
        "severity_confirmed": 0.6,
        "severity_unconfirmed": 0.3,
    },
    "rent": {
        "patterns": [
            re.compile(r"\bRENT\b|\bLEASE\b|\bHOUSE\s+RENT\b|\bLANDLORD\b", re.I),
        ],
        "severity_confirmed": 0.1211,
        "severity_unconfirmed": 0.0926,
        "inverted": True,  # flag triggers if pattern is ABSENT
    },
    "spend_balance": {
        "patterns": [],  # computed from total_credits vs total_debits
        "severity_confirmed": 0.6025,
        "severity_unconfirmed": 0.6025,
    },
}


# ─────────────────────────────────────────────────────────────────────────
# STEP 1: LOAD FEATURES
# ─────────────────────────────────────────────────────────────────────────

def load_features(features_csv: str = FEATURES_CSV) -> pd.DataFrame:
    if not Path(features_csv).exists():
        print(f"❌ {features_csv} not found. Run Agent 0 first.")
        sys.exit(1)
    df = pd.read_csv(features_csv)

    # ── Load training medians from agents_012.py output ──────────────────
    # training_medians.json is saved during training and contains
    # actual median values for every feature from the 22K+ gig worker cohort.
    # This includes EXT_SOURCE (credit bureau scores) and cred_/loan_ columns.
    # For thin-file gig workers like Raju, EXT_SOURCE is None — we fill with
    # cohort median so the model sees "average creditworthiness" not a blank.
    if Path(MEDIANS_JSON).exists():
        with open(MEDIANS_JSON) as f:
            medians = json.load(f)
        print(f"  Loaded {len(medians)} training medians from {MEDIANS_JSON}")
    else:
        # Fallback hardcoded values — only used if training_medians.json missing
        # Generate it: python3 -c "import pandas as pd, json; X=pd.read_csv('X_train.csv',index_col=0); json.dump(X.median().to_dict(), open('training_medians.json','w'), indent=2)"
        print(f"  ⚠ {MEDIANS_JSON} not found — using fallback medians")
        print(f"    Run: python3 agents_012.py --mode train  to generate it")
        medians = {
            'EXT_SOURCE_1':    0.4637,
            'EXT_SOURCE_2':    0.5143,
            'EXT_SOURCE_3':    0.5297,
            'ext_source_mean': 0.4987,
            'ext_source_std':  0.1823,
            'ext_source_min':  0.3641,
            'cred_payment_discipline':     0.8741,
            'cred_obligation_fulfillment': 0.9124,
            'cred_savings_ratio':          0.0523,
            'cred_debt_income_ratio':      0.4215,
            'cred_emi_income_ratio':       0.1832,
            'loan_loan_income_ratio':      0.3147,
            'loan_dti_ratio':              0.3521,
            'loan_dti_flag':               0.0,
            'loan_employment_years':       2.3,
            'loan_high_interest_flag':     0.0,
            'loan_loan_default_rate':      0.1134,
            'income_vs_plfs_ratio':        1.0,
        }

    # Fill all missing/NaN columns with training medians
    for col, val in medians.items():
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(val)
        else:
            df[col] = val

    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.fillna(0, inplace=True)
    return df


# ─────────────────────────────────────────────────────────────────────────
# STEP 2: COMPUTE BEHAVIORAL SCORE (0–10)
# ─────────────────────────────────────────────────────────────────────────

def compute_behavioral_score(row: pd.Series) -> dict:
    """
    3-group behavioral scoring matching AGENT0-RESULT-final5.json logic.

    Group A — Social Trust Graph (rootedness, obligations, stability)
    Group B — Behavioral Velocity (UPI + credit + loan signals)
    Group C — Derived Interactions (cross-feature non-linear signals)

    Returns dict with group scores + total (0–10).
    """
    eps = 1e-6

    # ── Group A: Social Trust Graph ───────────────────────────────────────
    # Rootedness = obligation fulfillment x income stability
    obligation     = float(row.get('upi_obligation_fulfillment_rate', 0.5))
    ior            = float(row.get('upi_inflow_outflow_ratio', 1.0))
    income_cv      = float(row.get('upi_income_regularity_cv', 0.35))
    ext_mean       = float(row.get('ext_source_mean', 0.4987))
    ext_min        = float(row.get('ext_source_min', 0.3641))
    monthly_income = float(row.get('AMT_INCOME_MONTHLY', 20000))

    # Rootedness: 0–1 (obligation fulfillment × income stability)
    income_stability = max(0, 1 - income_cv)
    rootedness       = 0.60 * obligation + 0.40 * income_stability

    # External credit anchor (0 for thin file → use ext medians)
    credit_anchor    = 0.50 * ext_mean + 0.30 * ext_min + 0.20 * (1 - float(row.get('ext_source_std', 0.18)))

    # FOIR proxy — annuity as % of monthly income (lower = better)
    annuity          = float(row.get('AMT_ANNUITY', 3750))
    foir             = min(annuity / (monthly_income + eps), 1.0)
    foir_score       = max(0, 1 - foir)   # higher FOIR = worse

    group_a = np.clip(
        0.40 * rootedness + 0.35 * credit_anchor + 0.25 * foir_score,
        0, 1
    )

    # ── Group B: Behavioral Velocity ─────────────────────────────────────
    streak           = float(row.get('upi_utility_payment_streak', 0))
    diversity        = float(row.get('upi_merchant_diversity_score', 0.5))
    spending_vel     = float(row.get('upi_spending_velocity', 0.3))
    crunch_recovery  = float(row.get('upi_cash_crunch_recovery_speed', 1.0))
    recurring        = float(row.get('upi_recurring_payment_ratio', 0.5))
    success_rate     = float(row.get('upi_success_rate', 1.0))
    fraud_rate       = float(row.get('upi_fraud_rate', 0.0))
    cred_savings     = float(row.get('cred_savings_ratio', 0.05))
    loan_default     = float(row.get('loan_loan_default_rate', 0.11))

    # Normalize streak to 0-1 (max meaningful streak = 18 months)
    streak_norm    = min(streak / 18.0, 1.0)
    # Lower spending volatility = better
    spend_stability= max(0, 1 - spending_vel)
    # Recovery speed: >1 = recovered, clip to 0-1
    recovery_norm  = min(crunch_recovery / 1.5, 1.0)
    # Fraud rate: lower is better
    fraud_score    = 1 - min(fraud_rate, 1.0)

    group_b = np.clip(
        0.20 * obligation
        + 0.15 * streak_norm
        + 0.15 * diversity
        + 0.12 * spend_stability
        + 0.10 * recurring
        + 0.10 * recovery_norm
        + 0.08 * success_rate
        + 0.05 * fraud_score
        + 0.05 * (1 - min(loan_default / 0.3, 1.0))  # lower loan default rate = better
        ,
        0, 1
    )

    # ── Group C: Derived Interactions ────────────────────────────────────
    # Rootedness × capacity: high obligation + low FOIR = best
    rootedness_x_capacity = rootedness * (1 - foir)

    # Surplus ratio: positive surplus = net saver
    surplus_ratio = np.clip(1 - 1 / (ior + eps), -1, 1)
    surplus_norm  = (surplus_ratio + 1) / 2   # map to 0-1

    # Spend trend: savings_ratio - debt_ratio (positive = accumulating wealth)
    cred_debt  = float(row.get('cred_debt_income_ratio', 0.42))
    spend_trend= np.clip(cred_savings - cred_debt, -1, 1)
    spend_norm = (spend_trend + 1) / 2

    # Income trend: inflow_outflow - 1 (positive = earning more than spending)
    income_trend = np.clip(ior - 1, -1, 1)
    income_norm  = (income_trend + 1) / 2

    # PLFS validation: income vs benchmark (1.0 = at benchmark)
    plfs_ratio = float(row.get('income_vs_plfs_ratio', 1.0))
    plfs_score = np.clip(plfs_ratio / 2.0, 0, 1)  # cap at 2x benchmark

    group_c = np.clip(
        0.30 * rootedness_x_capacity
        + 0.25 * surplus_norm
        + 0.20 * income_norm
        + 0.15 * spend_norm
        + 0.10 * plfs_score
        ,
        0, 1
    )

    # ── Total behavioral score (0–10) ─────────────────────────────────────
    # Weights match master dataset feature group importance
    total_raw = (
        0.35 * group_a    # Social Trust Graph
        + 0.40 * group_b  # Behavioral Velocity
        + 0.25 * group_c  # Derived Interactions
    )
    total_score = round(float(np.clip(total_raw * 10, 0, 10)), 2)

    return {
        "group_a_social_trust":     round(float(group_a), 4),
        "group_b_behavioral_vel":   round(float(group_b), 4),
        "group_c_derived":          round(float(group_c), 4),
        "step3_behavioral_score":   total_score,
    }


# ─────────────────────────────────────────────────────────────────────────
# STEP 3: RED FLAG DETECTION
# ─────────────────────────────────────────────────────────────────────────

def detect_red_flags(row: pd.Series, transactions: list) -> list:
    """
    Detect red flags from transaction narrations and feature values.

    Flags:
      gambling      — detected from transaction narrations
      rent          — absent rent payments in statement (inverted)
      spend_balance — total debits > total credits (net outflow)
    """
    flags = []

    # ── Gambling detection ────────────────────────────────────────────────
    gambling_pattern = re.compile(
        r"\bDREAM\s*11\b|\bRUMMY\b|\bBETTING\b|\bCASINO\b|\bMPL\b|\bWINZO\b|\bGAME\s*CASH\b",
        re.I
    )
    gambling_txns = [
        t for t in transactions
        if gambling_pattern.search(t.get('narration_clean', '') or t.get('narration', ''))
    ]
    gambling_confirmed = len(gambling_txns) >= 3  # 3+ gambling transactions = confirmed
    gambling_severity  = 0.6 if gambling_confirmed else 0.3
    flags.append({
        "flag":      "gambling",
        "severity":  gambling_severity,
        "confirmed": gambling_confirmed,
        "detail":    f"{len(gambling_txns)} gambling transactions detected" if gambling_txns
                     else "No gambling transactions found",
    })

    # ── Rent stress detection ─────────────────────────────────────────────
    rent_count    = int(row.get('rent_payment_count', 0))
    n_months      = max(row.get('upi_utility_payment_streak', 1), 1)
    # If rent count = 0 in a 12+ month statement → stress signal
    rent_absent   = rent_count == 0
    rent_confirmed= rent_absent  # confirmed if truly no rent payments
    rent_severity = 0.1211 if rent_confirmed else 0.0926
    flags.append({
        "flag":      "rent",
        "severity":  rent_severity,
        "confirmed": rent_confirmed,
        "detail":    f"No rent payments found in {n_months} months" if rent_absent
                     else f"Rent paid in {rent_count} transactions",
    })

    # ── Spend/balance detection ───────────────────────────────────────────
    # Total debits > total credits = net outflow = stress signal
    ior          = float(row.get('upi_inflow_outflow_ratio', 1.0))
    spend_stress = ior < 1.0   # spending more than earning
    flags.append({
        "flag":      "spend_balance",
        "severity":  0.6025,
        "confirmed": spend_stress,
        "detail":    f"Net outflow detected — inflow/outflow ratio = {ior:.4f}" if spend_stress
                     else f"Net saver — inflow/outflow ratio = {ior:.4f}",
    })

    return flags


# ─────────────────────────────────────────────────────────────────────────
# STEP 4: COMPUTE SCORE ADJUSTMENT FOR AGENT 4
# ─────────────────────────────────────────────────────────────────────────

def compute_score_adjustment(behavioral_score: float,
                              baseline_score: float,
                              red_flags: list) -> tuple:
    """
    Maps behavioral_delta to a GigScore adjustment (+0 to +5).
    Matches the logic in AGENT0-RESULT-final5.json exactly.

    Returns: (score_adjustment, behavioral_delta)
    """
    behavioral_delta = round(behavioral_score - baseline_score, 4)

    # Base adjustment from delta
    if behavioral_delta > 3.5:
        adj = 4
    elif behavioral_delta > 2.5:
        adj = 3
    elif behavioral_delta > 1.0:
        adj = 2
    elif behavioral_delta > 0.0:
        adj = 1
    else:
        adj = 0

    # Reduce by confirmed red flags (min 0)
    confirmed_flags = sum(1 for f in red_flags if f['confirmed'])
    adj = max(0, adj - confirmed_flags)

    return adj, behavioral_delta


# ─────────────────────────────────────────────────────────────────────────
# STEP 5: COMPUTE SOCIAL TRUST SCORE (0–100) for Agent 4 Layer 2
# ─────────────────────────────────────────────────────────────────────────

def compute_social_trust_score(row: pd.Series) -> float:
    """
    Social trust score for Agent 4's Layer 2 blend (10% weight).

    Based on:
      - Edge stability  : recurring payment ratio (pay same people monthly)
      - Node reliability: obligation fulfillment rate
      - Flow stability  : inflow/outflow ratio
      - Temporal depth  : utility payment streak
      - Network breadth : merchant diversity

    Returns: score 0–100
    """
    eps = 1e-6

    edge_stability  = float(row.get('upi_recurring_payment_ratio', 0.5))
    node_reliability= float(row.get('upi_obligation_fulfillment_rate', 0.5))
    ior             = float(row.get('upi_inflow_outflow_ratio', 1.0))
    flow_stability  = min(ior / 2.0, 1.0)
    diversity       = float(row.get('upi_merchant_diversity_score', 0.5))
    streak          = float(row.get('upi_utility_payment_streak', 0))
    temporal        = min(streak / 12.0, 1.0)

    # Brownie points for exceptional signals
    bonus = 0.0

    # Platform density bonus: 3000+ gig income transactions = embedded worker
    platform_txns = int(row.get('platform_income_txn_count', 0))
    if platform_txns >= 3000:
        bonus += 0.03
    elif platform_txns >= 1000:
        bonus += 0.01

    # Network density bonus: 30+ unique VPA counterparties
    unique_vpas = int(row.get('upi_unique_merchants', 0))
    if unique_vpas >= 30:
        bonus += 0.02

    raw_score = np.clip(
        0.25 * edge_stability
        + 0.30 * node_reliability
        + 0.20 * flow_stability
        + 0.15 * diversity
        + 0.10 * temporal
        + bonus,
        0, 1
    )

    return round(float(raw_score * 100), 2)


# ─────────────────────────────────────────────────────────────────────────
# STEP 6: COMPUTE BEHAVIORAL SAFE SCORE
# ─────────────────────────────────────────────────────────────────────────

def compute_behavioral_safe_score(model_default_prob: float,
                                   red_flags: list) -> float:
    """
    Behavioral safe score = P(non-default) adjusted for red flags.
    Matches AGENT0-RESULT-final5.json format.
    """
    base_safe = 1.0 - model_default_prob

    # Each confirmed red flag slightly reduces safe score
    for flag in red_flags:
        if flag['confirmed']:
            base_safe -= flag['severity'] * 0.05  # small reduction

    return round(float(np.clip(base_safe, 0, 1)), 6)


# ─────────────────────────────────────────────────────────────────────────
# MAIN PIPELINE
# ─────────────────────────────────────────────────────────────────────────

def run_agent3(features_csv:  str = FEATURES_CSV,
               agent0_json:   str = OUTPUT_JSON_A0,
               output_json:   str = OUTPUT_JSON) -> list:

    print("=" * 68)
    print("GigScore — Agent 3: Social Trust + Behavioral Scoring")
    print("Barclays Hack-O-Hire 2026 · Team GigScore · Plaksha University")
    print("=" * 68)

    # ── Load features ─────────────────────────────────────────────────────
    print(f"\n  Loading features from {features_csv}...")
    features_df = load_features(features_csv)
    print(f"  Loaded {len(features_df)} applicant(s), {features_df.shape[1]} features")

    # ── Load transactions for red flag detection ──────────────────────────
    transactions = []
    if Path(agent0_json).exists():
        with open(agent0_json) as f:
            a0 = json.load(f)
        transactions = a0.get('transactions', [])
        print(f"  Loaded {len(transactions):,} transactions for red flag detection")
    else:
        print(f"  ⚠ {agent0_json} not found — red flag detection limited")

    # ── Load Agent 2 default_prob ─────────────────────────────────────────
    # Agent 2 computes the real XGBoost default probability for each applicant.
    # We use it here for behavioral_safe_score. Falls back to 0.20 if missing.
    a2_result = {}
    a2_path   = Path(AGENT2_RESULT)
    if not a2_path.exists():
        # try generic pattern agent2_result_*.json
        matches = list(Path('.').glob('agent2_result_*.json'))
        if matches:
            a2_path = matches[0]
    if a2_path.exists():
        with open(a2_path) as f:
            a2_result = json.load(f)
        print(f"  Loaded Agent 2 result from {a2_path.name} "
              f"(default_prob={a2_result.get('default_prob', '?')})")
    else:
        print(f"  ⚠ Agent 2 result not found — using default_prob=0.20")
        print(f"    Run: python3 agents_012.py --mode score --skip_agent0")

    # ── Cohort baseline score (from master dataset) ───────────────────────
    COHORT_BASELINE = 3.55  # avg behavioral score across 22K+ gig workers

    results = []

    for _, row in features_df.iterrows():
        persona_id      = str(row.get('persona_id', 'unknown'))
        applicant_token = str(row.get('applicant_token', 'APPL_unknown'))
        monthly_income  = float(row.get('AMT_INCOME_MONTHLY', 20000))

        print(f"\n  Processing: {persona_id} ({applicant_token})")

        # Step 1: Behavioral score
        beh         = compute_behavioral_score(row)
        step3_score = beh['step3_behavioral_score']

        # Step 2: Red flags
        red_flags       = detect_red_flags(row, transactions)
        confirmed_count = sum(1 for f in red_flags if f['confirmed'])

        # Step 3: Score adjustment
        adj, delta = compute_score_adjustment(step3_score, COHORT_BASELINE, red_flags)

        # Step 4: Social trust score
        social_trust = compute_social_trust_score(row)

        # Step 5: Behavioral safe score — use Agent 2 default_prob if available
        model_default_prob = float(a2_result.get('default_prob', 0.20))
        behavioral_safe    = compute_behavioral_safe_score(model_default_prob, red_flags)

        # Zone recommendation
        zone = "CLEAR" if confirmed_count <= 1 else "REVIEW"

        # ── Build signal dict matching original JSON format ───────────────
        behavioral_signals = {
            "upi_success_rate":             float(row.get('upi_success_rate', 1.0)),
            "upi_inflow_outflow_ratio":     float(row.get('upi_inflow_outflow_ratio', 1.0)),
            "upi_merchant_diversity_score": float(row.get('upi_merchant_diversity_score', 0.5)),
            "income_regularity_cv":         float(row.get('upi_income_regularity_cv', 0.35)),
            "obligation_fulfillment_rate":  float(row.get('upi_obligation_fulfillment_rate', 0.5)),
            "spending_velocity":            float(row.get('upi_spending_velocity', 0.3)),
            "age":                          float(row.get('age', 32.0)),
            "years_employed":               float(row.get('years_employed', 1.5)),
            "employment_age_ratio":         float(row.get('employment_age_ratio', 0.05)),
            "monthly_income":               round(monthly_income, 2),
        }

        record = {
            "persona_id":               persona_id,
            "applicant_token":          applicant_token,
            "step3_behavioral_score":   step3_score,
            "behavioral_delta":         delta,
            "score_adjustment":         adj,
            "zone_recommendation":      zone,
            "model_default_probability":round(model_default_prob, 6),
            "behavioral_safe_score":    behavioral_safe,
            "portfolio_safe_rate":      PORTFOLIO_SAFE_RATE,
            "confirmed_red_flag_count": confirmed_count,
            "red_flag_details":         [
                {
                    "flag":      f["flag"],
                    "severity":  round(f["severity"], 4),
                    "confirmed": f["confirmed"],
                }
                for f in red_flags
            ],
            "behavioral_signals":       behavioral_signals,
            # ── Extra fields for Agent 4 ──────────────────────────────────
            "social_trust_score":       social_trust,
            "group_scores": {
                "group_a_social_trust":   beh["group_a_social_trust"],
                "group_b_behavioral_vel": beh["group_b_behavioral_vel"],
                "group_c_derived":        beh["group_c_derived"],
            },
        }

        results.append(record)

        # ── Print summary ─────────────────────────────────────────────────
        print(f"  {'─' * 50}")
        print(f"  Behavioral score    : {step3_score} / 10")
        print(f"  Behavioral delta    : +{delta:.4f} vs cohort")
        print(f"  Score adjustment    : +{adj} GigScore points → Agent 4")
        print(f"  Social trust score  : {social_trust} / 100")
        print(f"  Zone                : {zone}")
        print(f"  Confirmed red flags : {confirmed_count}")
        for f in red_flags:
            icon = "🔴" if f['confirmed'] else "🟡"
            print(f"    {icon} {f['flag']:<20} severity={f['severity']:.4f} | {f.get('detail','')}")

    # ── Save output JSON ──────────────────────────────────────────────────
    with open(output_json, 'w') as f:
        json.dump(results, f, indent=2, default=str)

    # ── Print final summary ───────────────────────────────────────────────
    print()
    print("╔══════════════════════════════════════════════════════════════════╗")
    print("║              AGENT 3 COMPLETE                                   ║")
    print("╠══════════════════════════════════════════════════════════════════╣")
    for r in results:
        adj_str = f"+{r['score_adjustment']}" if r['score_adjustment'] >= 0 else str(r['score_adjustment'])
        print(f"║  {r['persona_id']:<20} score={r['step3_behavioral_score']:<5} "
              f"adj={adj_str:<3} trust={r['social_trust_score']:<6} zone={r['zone_recommendation']:<7}║")
    print("╠══════════════════════════════════════════════════════════════════╣")
    print(f"║  📄 {output_json:<61}║")
    print("╠══════════════════════════════════════════════════════════════════╣")
    print("║  NEXT: Agent 4 — Final GigScore + Explanation                   ║")
    print("╚══════════════════════════════════════════════════════════════════╝")

    return results


# ─────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="GigScore Agent 3 — Behavioral Scoring")
    parser.add_argument('--features', default=FEATURES_CSV,
                        help='Path to agent0_features.csv')
    parser.add_argument('--transactions', default=OUTPUT_JSON_A0,
                        help='Path to agent0_output.json')
    parser.add_argument('--output', default=OUTPUT_JSON,
                        help='Output path for agent3_output.json')
    args = parser.parse_args()

    run_agent3(
        features_csv = args.features,
        agent0_json  = args.transactions,
        output_json  = args.output,
    )
